import React, { useState } from 'react';
import { FiArrowDownRight, FiArrowUpRight, FiChevronDown, FiDownload, FiGithub, FiLinkedin, FiMail, FiMenu, FiX } from 'react-icons/fi';
import { SiAnsible, SiAzuredevops, SiDocker, SiGitlab, SiHelm, SiKubernetes, SiTerraform } from 'react-icons/si';
import './index.css';
import profile from './assets/me.png';
import resume from './assets/Resume.pdf';

const GITHUB = 'https://github.com/mishrasiddhant001';
const LINKEDIN = 'https://www.linkedin.com/in/siddhant-mishra-43584b198/';
const EMAIL = 'siddhantmishra1002@gmail.com';
const metrics = [['130+', 'pipeline definitions'], ['120+', 'Ansible playbooks'], ['~60%', 'fewer deployment failures'], ['200', 'pod Kubernetes environments'], ['100+', 'performance-test pods'], ['50+', 'applications stabilized']];

const projects = [
  { id:'gitlab-pipelines', number:'01', label:'Professional / Private Project', title:'GitLab CI/CD Pipeline Design & Management', summary:'Ground-up GitLab CI/CD pipelines powering a multi-language microservices platform.', problem:'A 130+ application microservices platform spanning Java, .NET, C++, Gradle, PHP, and Python needed consistent, reliable CI/CD from the ground up — not just automation for one stack, but a shared pipeline standard across all of them.', implementation:'Designed, built, and maintained GitLab CI/CD pipelines covering build automation, unit testing, enterprise-grade code signing, staged deployments, artifact publishing, and release orchestration. Configured and tuned self-hosted GitLab Runners on both Linux and Windows to improve concurrency, caching, and execution time, and integrated artifact repository publishing directly into the pipeline flow.', impact:'Gave 130+ applications and microservices a single, dependable delivery path — cutting manual release steps and giving teams a consistent build-to-release process regardless of language or stack.', stack:['GitLab CI/CD', 'GitLab Runners (Linux/Windows)', 'Maven', 'Gradle', '.NET', 'WinRM', 'JFrog Artifactory'], flow:['Source push', 'Build & unit test', 'Code signing', 'Artifact publish', 'Staged deployment', 'Release'] },
  { id:'runners', number:'02', label:'Professional / Private Project', title:'Ephemeral GitLab Runners on Azure', summary:'Elastic, VM-based CI capacity that exists only for the job that needs it.', problem:'Always-on runner VMs consumed infrastructure even when pipeline demand was variable.', implementation:'Designed Terraform-driven Azure runner provisioning so CI jobs receive a VM runner on demand and it is decommissioned when work completes.', impact:'Right-sized CI infrastructure to workload demand, avoiding the operational drag of large, permanently provisioned runner fleets.', stack:['Azure', 'Terraform', 'GitLab CI/CD', 'GitLab Runner'], flow:['GitLab pipeline', 'Runner request', 'Terraform', 'Azure VM', 'CI/CD job', 'VM decommissioned'] },
  { id:'harness', number:'03', label:'Professional / Private Project', title:'GitLab CI/CD → Harness migration', summary:'A scalable migration path for enterprise pipeline-as-code and delivery governance.', problem:'Pipeline standardization needed to move from GitLab CI/CD to Harness without disrupting established Ansible deployment automation.', implementation:'Refactored and implemented 130+ pipeline definitions, built reusable Maven, .NET, and security-scanning templates, and provisioned Helm-based Harness Delegates on Kubernetes.', impact:'Created a governed delivery foundation for 130+ applications and microservices while preserving the automation teams already relied on.', stack:['Harness', 'GitLab CI/CD', 'Kubernetes', 'Helm', 'Ansible'], flow:['GitLab CI/CD', 'Pipeline-as-Code migration', 'Harness', 'Harness Delegates', 'Kubernetes / Helm', 'Ansible', 'Target applications'] },
  { id:'landing-page', number:'04', label:'Professional / Private Project', title:'Harness Landing Page', summary:'An internal platform surface for safe, discoverable delivery operations.', problem:'Teams needed a consistent way to navigate project scopes, environment boundaries, permissions, and shared templates.', implementation:'Developed a centralized landing page around project scopes, access permissions, reusable-template governance, review workflows, and development/production separation.', impact:'Improved operational visibility around access, environments, and approved delivery patterns for teams using the platform.', stack:['Harness', 'Platform Engineering', 'RBAC', 'CI/CD Governance'], flow:['Teams', 'Project scopes', 'Access permissions', 'Reviewed templates', 'Development / Production'] },
  { id:'ansible', number:'05', label:'Professional / Private Project', title:'Enterprise Ansible Automation', summary:'Repeatable operational automation for deployment and environment management.', problem:'Application delivery, configuration, and operational tasks required dependable automation across environments.', implementation:'Developed and maintained 120+ Jinja2-templated playbooks for application deployments, database migrations, certificate management, service orchestration, and configuration management.', impact:'Stabilized delivery across 50+ applications and microservices, contributing to approximately 60% fewer deployment failures through repeatable configuration, backup, and rollback practices.', stack:['Ansible', 'Jinja2', 'GitLab CI/CD', 'Harness', 'Linux', 'Windows'], flow:['CI/CD trigger', 'Templated configuration', 'Ansible playbooks', 'Services & databases', 'Validated deployment'] },
  { id:'devsecops', number:'06', label:'Professional / Private Project', title:'DevSecOps CI/CD', summary:'Security and code intelligence embedded directly in the delivery lifecycle.', problem:'Quality, dependency, licensing, and code metrics needed to be actionable before software reached deployment.', implementation:'Integrated SAST, SCA, and license-compliance scanning into pipelines, and built a custom tool that publishes severity-grouped scan findings directly into merge-request comments.', impact:'Shifted security, dependency, and license feedback into code review—where risk can be addressed before release decisions are made.', stack:['SonarQube', 'SCA & reachability scanning', 'OWASP Dependency-Check', 'License compliance scanning', 'Code metrics reporting', 'Bash'], flow:['Source', 'Build', 'SAST / quality', 'Dependency analysis', 'License scanning', 'Artifact', 'Deployment'] },
  { id:'vault', number:'07', label:'Professional / Private Project', title:'HA Secrets Management for CI/CD', summary:'Centralized secrets, credentials, and certificate management for delivery automation.', problem:'CI/CD systems require controlled access to sensitive credentials and certificates while remaining highly available.', implementation:'Integrated HashiCorp Vault into CI/CD pipelines and worked with Vault HA clusters, unsealing, Raft storage, and HAProxy-based high availability.', impact:'Established a controlled, highly available path for secrets and certificates to reach delivery workflows without embedding them in pipeline configuration.', stack:['HashiCorp Vault', 'HAProxy', 'Raft', 'CI/CD', 'Security'], flow:['Applications', 'CI/CD', 'HashiCorp Vault', 'Vault HA cluster', 'Raft storage', 'HAProxy'] },
];
const skillGroups = [
  ['CI/CD', 'GitLab CI/CD · Harness · Jenkins'],
  ['Build Automation', 'Maven · Gradle · npm · Composer · .NET Core/Framework'],
  ['Infrastructure as Code', 'Terraform · Ansible'],
  ['Containers & Orchestration', 'Docker · Kubernetes · Helm'],
  ['Cloud', 'Azure · AWS · GCP'],
  ['Security / DevSecOps', 'SonarQube · SCA & reachability scanning · OWASP Dependency-Check · license & code-metrics scanning · HashiCorp Vault'],
  ['Artifact Management', 'Sonatype Nexus · JFrog Artifactory'],
  ['Systems', 'Linux · Windows Server · IIS · WinRM · NGINX · Apache · HAProxy'],
  ['Scripting', 'Python · Bash · PowerShell'],
  ['Databases', 'MySQL · MSSQL · Liquibase · phpMyAdmin'],
  ['Collaboration Tools', 'Git · GitHub · GitLab · VS Code · Postman · Jira · Jupyter · Colab']
];

const projectArchive = [
  { id:'gitlab-pipelines', title:'GitLab CI/CD Pipeline Design & Management', summary:'Built and operate 130+ GitLab CI/CD pipelines from scratch across a multi-language microservices platform.', tags:['GitLab CI/CD', 'Multi-language Builds', 'Release Engineering'], description:'Designed, built, and maintain GitLab CI/CD pipelines for a 130+ application microservices platform spanning Java, .NET, C++, Gradle, PHP, and Python — covering build automation, unit testing, enterprise-grade code signing, staged deployments, artifact publishing, and release orchestration.', details:['Configured and tuned self-hosted GitLab Runners on Linux and Windows for pipeline concurrency, caching, and execution efficiency.','Implemented enterprise-grade code signing in-pipeline via WinRM for Windows build targets.','Wired artifact publishing into JFrog Artifactory directly from pipeline stages.','Provided L2 support to keep legacy pipelines reliable during day-to-day operation.'], metrics:['130+ pipeline-driven applications', '8+ languages/build stacks'], stack:['GitLab CI/CD', 'GitLab Runners (Linux/Windows)', 'Maven', 'Gradle', '.NET', 'WinRM', 'Sonatype Nexus Repository'] },
  { id:'migration', title:'GitLab to Harness CI/CD Migration', summary:'Migrated 130+ pipelines from GitLab CI to Harness across 8+ platforms.', tags:['Harness', 'GitLab CI', 'Kubernetes/Helm'], description:'Led the end-to-end migration from GitLab CI/CD to Harness. Translated GitLab CI YAML constructs including rules, variables, artifacts, and script blocks into Harness equivalent CI and respective triggers. Built reusable Step, Stage, and Pipeline templates for Maven builds, .NET builds, Ansible deploys, and security scanning. Provisioned Harness Delegates on Kubernetes with Helm and retained existing Ansible automation throughout the cutover.', details:['Debugged .NET Framework assembly version conflicts, Windows command-line limits, and MSBuild path issues on Windows Delegates.','Built reusable CI environment templates covering Linux with Maven/Node, Windows with .NET Framework/Core (including legacy-to-latest version support and PostSharp), and Windows with Gradle - reducing JFrog storage costs by eliminating unnecessary Docker image publishing.', 'Built a reusable code-signing template (WinRM + Harness Delegates) to sign JARs, DLLs, and EXEs directly in pipeline.',
], metrics:['130+ pipeline definitions', '8+ platforms'], stack: [ 'Harness', 'GitLab CI/CD', 'Kubernetes', 'Helm', 'Java', '.NET', 'Maven', 'Gradle', 'Ansible', 'JFrog Artifactory', 'Node.js', 'Python'] },
  { id:'endor', title:'CI/CD-Integrated Security Scanning', summary:'Built CI/CD-integrated Endor Labs SCA and reachability scanning with automated MR Comments by mapping the Sarif .', tags:['SCA', 'SARIF', 'DevSecOps'], description:'Designed and rolled out CLI-based software composition analysis (SCA) and reachability-based vulnerability scanning across GitLab and Harness  CI, covering Java/Maven and .NET/Windows build stacks. Built a custom Bash tool that parses SARIF output and publishes severity-grouped findings as GitLab Merge Request comments, putting actionable security feedback directly into the review workflow.', details:['Configured SARIF output and native Harness security-testing ingestion for scan results.','Handled MR comment payload limits and severity-to-label mapping from the SARIF level field.','Fixed PHP/Python host-check failures and Docker image baking for the scanning CLI.','Resolved Windows PowerShell ANSI and UTF-8 BOM handling.','Integrated SonarQube SAST and code-quality analysis into GitLab CI and Harness pipelines, configuring project-level quality gates and surfacing vulnerabilities, bugs, code smells, and coverage metrics before deployment.'], stack:['Endor Labs','SCA scanning', 'Bash', 'GitLab CI', 'Harness STO', 'SonarQube', 'OWASP Dependency-Check'] },
  { id:'ansible-framework', title:'Ansible Automation Framework', summary:'120+ playbooks automating deployment, DB, and certificate management.', tags:['Ansible', 'Jinja2', 'PowerShell'], description:'Built and continue to maintain an Ansible automation framework of 120+ playbooks for application deployments, database migrations, certificate management, service orchestration, and environment-specific configuration. Jinja2 templating keeps configuration repeatable across environments. The framework is integrated directly into GitLab CI/CD and Harness workflows. It brings operational changes into the same controlled path as application delivery.', details:['Automated Windows IIS site creation with HTTPS, SNI, ARR, and URL Rewrite.','Built date-stamped database backup automation with seven-day retention cleanup.','Templated multi-node cluster configuration with Jinja2-generated SQL.','Integrated hashi_vault lookups for secret retrieval inside playbooks.'], metrics:['120+ playbooks'], stack:['Ansible', 'Jinja2', 'PowerShell', 'Bash', 'HashiCorp Vault'] },
  { id:'vault-ha', title:'Vault HA and Secrets Management', summary:'Ran and recovered a 3-node Vault HA cluster with HAProxy.', tags:['Vault', 'HAProxy', 'Secrets Mgmt'], description:'Owned secrets management with a three-node HashiCorp Vault Raft HA cluster, including deployment, unsealing, and HAProxy-based high-availability routing. Integrated Vault with CI/CD pipelines for secure secrets, credentials, and certificate delivery. Investigated and recovered HA behavior during an outage rather than treating the cluster as a black box. Added scripts to make KV data movement and certificate maintenance safer to operate.', details:['Resolved an HAProxy 503 outage caused by both nodes returning standby responses, by forcing a clean leader election.','Wrote PowerShell scripts for recursive KV v2 export to CSV and CSV-to-Vault upload with environment path rewriting.','Renewed wildcard TLS certificates across Java keystores and Vault/HAProxy PEM configuration.'], metrics:['3-node Raft HA cluster'], stack:['HashiCorp Vault', 'HAProxy', 'PowerShell', 'Raft'] },
  { id:'ephemeral-runners', title:'Ephemeral GitLab Runners', summary:'Auto-provisioned and decommissioned VM runners to eliminate idle infrastructure.', tags:['Terraform', 'Azure', 'GitLab Runners'], description:'Designed and implemented ephemeral GitLab Runner infrastructure on Azure with Terraform. Runner VMs are dynamically provisioned for CI/CD jobs and automatically decommissioned when execution finishes. This removes the need for large always-on runner fleets while retaining pipeline concurrency. The model aligns infrastructure use with actual build demand.', details:['Tied the Terraform-driven VM lifecycle to CI/CD job triggers.','Reduced the always-on compute footprint while preserving pipeline capacity.'], stack:['Terraform', 'Microsoft Azure', 'GitLab CI/CD'] },
  { id:'delegate-load', title:'Kubernetes Delegates and Load Testing', summary:'Helm-based delegate clusters running up to 200 pods, plus large-scale agent load testing.', tags:['Kubernetes', 'Helm', 'Load Testing'], description:'Designed and managed Helm-based Kubernetes Delegate clusters supporting up to 200 pods. The clusters enable Harness to run Ansible playbooks through containerized runners. In parallel, built a performance-testing environment that launched 100+ agent pods for realistic load and scale validation of an agent-based monitoring service.', details:['Designed Helm charts for Delegate scaling and resource limits.','Coordinated 100+ concurrent agent pods for load simulation.'], metrics:['Up to 200 Delegate pods', '100+ load-test agent pods'], stack:['Kubernetes', 'Helm', 'Harness Delegates', 'Docker'] },
  { id:'artifactory', title:'Artifact Repository Migration', summary:'Migrated artifact repositories to JFrog Artifactory and rebuilt governance across teams.', tags:['JFrog', 'Nexus', 'Migration'], description:'Led the strategy to migrate artifact repositories from Sonatype Nexus to JFrog Artifactory. Defined repository structures across local, remote, and virtual repositories, along with version management and controlled internal distribution. Built and validated cross-platform migration tooling before wider rollout. Updated build configurations so teams could consume artifacts through the new governed registry path.', details:['Ran a JFrog proof of concept with Docker, Docker Compose, and PostgreSQL.','Reworked Maven settings.xml mirror and exclusion patterns for Artifactory.','Migrated npm and yarn registries from Nexus to JFrog api/npm paths.'], stack:['JFrog Artifactory', 'Sonatype Nexus', 'Docker', 'Maven'] },
  { id:'oidc', title:'OIDC-Federated Cloud Access for CI/CD', summary:'Eliminated stored cloud secrets using short-lived OIDC tokens.', tags:['OIDC', 'Harness', 'Zero-Trust Security'], description:'Architected an OIDC-federated cloud access pattern to remove stored, long-lived cloud credentials from CI/CD. Pipelines exchange a short-lived signed identity token for temporary, scoped cloud credentials at runtime instead of referencing static secrets — narrowing the blast radius of a compromised credential while keeping cloud access fully automated.', details:['Removed static cloud credentials from pipeline configuration and secret stores.','Designed the signed OIDC token to temporary, scoped cloud credential exchange flow.','Reduced credential blast radius because every issued credential expires within an hour.'], metrics:['5-minute identity token TTL', '1-hour cloud credential TTL'], stack:['Harness', 'OIDC', 'Cloud IAM federation'] },
  { id:'apk', title:'APK Build Automation Tool', summary:'Streamlit and Docker app automating client-branded APK builds.', tags:['Python', 'Streamlit', 'Docker'], description:'Built a Python Streamlit and Docker web application to automate client-branded APK builds for Android Mobile, Android TV, and Roku. The tool applies client-specific branding at build time and reduces manual build work. It was paired with Terraform and Python automation for EC2 provisioning that supports Laravel backend and CMS dashboard deployments. The result is a more repeatable handoff from configuration to a build-ready environment.', details:['Automated client-specific branding at APK build time.','Supported Android Mobile, Android TV, and Roku targets.','Paired build automation with Terraform and Python EC2 provisioning.'], stack:['Python', 'Streamlit', 'Docker', 'Terraform', 'AWS EC2'] },
];

function Flow({ items }) { return <ol className="flow" aria-label="Architecture flow">{items.map((item) => <li key={item}>{item}</li>)}</ol>; }
function ProjectCard({ project, featured }) { return <article className={`project-card ${featured ? 'featured-project' : ''}`}><div className="project-topline"><span>{project.number}</span><span className="private-label">{project.label}</span></div><h3>{project.title}</h3><p className="project-summary">{project.summary}</p><div className="project-detail"><strong>Problem</strong><p>{project.problem}</p></div><div className="project-detail"><strong>Implementation</strong><p>{project.implementation}</p></div><div className="project-flow"><Flow items={project.flow} /></div><div className="project-detail impact"><strong>Result</strong><p>{project.impact}</p></div><ul className="tags">{project.stack.map((item) => <li key={item}>{item}</li>)}</ul></article>; }
function ProjectArchiveCard({ project, isOpen, onToggle }) {
  const panelId = `${project.id}-details`;
  return <article className={`project-card archive-card ${isOpen ? 'is-open' : ''}`}>
    <button className="archive-card-trigger" type="button" aria-expanded={isOpen} aria-controls={panelId} onClick={onToggle}>
      <span className="archive-card-heading"><span className="archive-card-title">{project.title}</span><FiChevronDown className="archive-chevron" aria-hidden="true" /></span>
      <span className="archive-card-summary">{project.summary}</span>
      <span className="archive-tags">{project.stack.map((tag) => <span key={tag}>{tag}</span>)}</span>
    </button>
    <div id={panelId} className="archive-details" aria-hidden={!isOpen}>
      <div className="archive-details-inner">
        <p>{project.description}</p>
        <ul className="archive-list">{project.details.map((detail) => <li key={detail}>{detail}</li>)}</ul>
        {project.metrics && <div className="archive-metrics">{project.metrics.map((metric) => <span key={metric}>{metric}</span>)}</div>}
      </div>
    </div>
  </article>;
}

function App() {
  const [isMenuOpen, setMenuOpen] = useState(false);
  const [openProjectId, setOpenProjectId] = useState(null);
  const navItems = [['Work', '#work'], ['Capabilities', '#capabilities'], ['Contact', '#contact']];
  const closeMenu = () => setMenuOpen(false);
  return <div className="site-shell">
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><a className="brand" href="#top" aria-label="Siddhant Mishra, home"><span>SM</span><b>Siddhant Mishra</b></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={isMenuOpen} onClick={() => setMenuOpen(!isMenuOpen)}>{isMenuOpen ? <FiX /> : <FiMenu />}</button><nav className={isMenuOpen ? 'nav-links open' : 'nav-links'} aria-label="Main navigation">{navItems.map(([label, href]) => <a key={href} href={href} onClick={closeMenu}>{label}</a>)}<a href={resume} className="nav-resume" target="_blank" rel="noreferrer" onClick={closeMenu}>Resume <FiDownload /></a></nav></header>
    <main id="main">
      <section id="top" className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span></span> DevOps Engineer · 2+ years</p><h1 id="hero-title">I build delivery systems teams depend on.</h1><p className="hero-intro">Siddhant Mishra architects CI/CD, infrastructure automation, Kubernetes platforms, and secure cloud delivery across all platforms.</p><p className="specialisms">CI/CD <i>•</i> Kubernetes <i>•</i> Terraform <i>•</i> Ansible <i>•</i> Cloud <i>•</i> DevSecOps</p><div className="hero-actions"><a href="#work" className="button primary">View  work <FiArrowDownRight /></a><a href={resume} target="_blank" rel="noreferrer" className="button secondary">Resume <FiDownload /></a></div><div className="hero-socials" aria-label="Social links"><a href={GITHUB} target="_blank" rel="noreferrer"><FiGithub /> GitHub <FiArrowUpRight /></a><a href={LINKEDIN} target="_blank" rel="noreferrer"><FiLinkedin /> LinkedIn <FiArrowUpRight /></a><a href="https://mail.google.com/mail/?view=cm&fs=1&to=siddhantmishra1002@gmail.com" target="_blank"  rel="noreferrer" > <FiMail /> Email </a></div></div><div className="hero-visual" aria-hidden="true"><div className="orbital orbital-one"></div><div className="orbital orbital-two"></div><div className="profile-frame"><img src={profile} alt="" /><div className="profile-tag"><span className="status-dot"></span> Delivery systems at scale</div></div><div className="terminal-card"><div><span></span><span></span><span></span></div><code><em>$</em> automate --reliably<br /><em>✓</em> pipeline delivery<br /><em>✓</em> infrastructure as code<br /><em>✓</em> secure by default</code></div></div></section>
      <section className="metrics-section" aria-labelledby="impact-title"><div className="section-intro compact"><p className="eyebrow">Impact at enterprise scale</p><h2 id="impact-title">The numbers behind the automation.</h2></div><div className="metrics-grid">{metrics.map(([value, label]) => <div className="metric" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
      <section id="work" className="work-section" aria-labelledby="work-title"><div className="section-intro"><p className="eyebrow">Selected work</p><h2 id="work-title">Engineering systems that make delivery resilient.</h2><p>Large-scale CI/CD migrations stay dependable when existing deployment automation is carried forward, not replaced. Security and quality gates belong in the delivery pipeline, not after it.</p><p>Enterprise projects are intentionally described at an architecture level; implementation details and company source remain private. <a href={GITHUB} target="_blank" rel="noreferrer">Browse GitHub <FiArrowUpRight /></a></p></div><div className="project-grid archive-grid">{projectArchive.map((project) => <ProjectArchiveCard key={project.id} project={project} isOpen={openProjectId === project.id} onToggle={() => setOpenProjectId(openProjectId === project.id ? null : project.id)} />)}</div></section>
      <section id="capabilities" className="capabilities-section" aria-labelledby="capabilities-title"><div className="section-intro"><p className="eyebrow">Technical capabilities</p><h2 id="capabilities-title">A practical platform engineering toolkit.</h2><p>Tools are organized by the problems they help solve—not by logo count.</p></div><div className="capability-feature"><div className="tool-icons"><SiGitlab /><SiTerraform /><SiAnsible /><SiKubernetes /><SiHelm /><SiDocker /><SiAzuredevops /></div><p>From build and artifact publishing to deployment, security controls, and operations, Siddhant works across the full delivery path.</p></div><div className="skills-grid">{skillGroups.map(([title, tools]) => <article key={title}><h3>{title}</h3><p>{tools}</p></article>)}</div></section>
      <section id="contact" className="contact-section" aria-labelledby="contact-title"><div><p className="eyebrow">CI/CD platforms · DevSecOps</p><h2 id="contact-title">Planning a CI/CD migration or stronger pipeline security?</h2><p>Let’s talk about delivery platforms that scale without breaking established automation—and bring security and quality checks into every release path.</p></div><div className="contact-actions"><a className="button primary" href="https://mail.google.com/mail/?view=cm&fs=1&to=siddhantmishra1002@gmail.com" target="_blank" rel="noreferrer"> Start a conversation <FiArrowUpRight /> </a><a className="button secondary" href={LINKEDIN} target="_blank" rel="noreferrer">Connect on LinkedIn <FiLinkedin /></a></div></section>
    </main>
    <footer>
  <a className="brand" href="#top">
    <span>SM</span>
    <b>Siddhant Mishra</b>
  </a>

  <p>DevOps Engineer · CI/CD · Platform Engineering</p>

  <a
    href="https://mail.google.com/mail/?view=cm&fs=1&to=siddhantmishra1002@gmail.com"
    target="_blank"
    rel="noreferrer"
  >
    {EMAIL}
  </a>

  <small>
    © {new Date().getFullYear()} Siddhant Mishra. All rights reserved.
  </small>
</footer>
  </div>;
}
export default App;