name: Deploy React App to GH Pages

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      node-modules-cache-key: ${{ steps.cache-key.outputs.key }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Cache node_modules
        id: cache-key
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Upload node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
          path: node_modules

      - name: Build React App
        run: CI=false npm run build

      - name: Upload Build Folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
